kongproject/kong/frontends/views.py
# -*- coding: utf-8 -*-
"""
"""
from flask import (Blueprint, request, render_template, flash,
    g, session, redirect, url_for)
from werkzeug import check_password_hash, generate_password_hash

from kong import db
from kong import search as search_module # don't override function name
from kong.users.forms import RegisterForm, LoginForm
from kong.users.models import User
from kong.threads.models import Thread
from kong.subreddits.models import Subreddit
from kong.users.decorators import requires_login
from kong.security.sec_util import secode_validate

mod = Blueprint('frontends', __name__, url_prefix='')

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

def home_subreddit():
    return Subreddit.query.get_or_404(1)

def get_subreddits():
    """
    important and widely imported method because a list of
    the top 30 subreddits are present on every page in the sidebar
    """
    subreddits = Subreddit.query.all()[:25]
    return subreddits

def process_thread_paginator(trending=False, rs=None, subreddit=None):
    """
    abstracted because many sources pull from a thread listing
    source (subreddit permalink, homepage, etc)
    """
    threads_per_page = 15
    cur_page = request.args.get('page') or 1
    cur_page = int(cur_page)
    thread_paginator = None

    # if we are passing in a resultset, that means we are just looking to
    # quickly paginate some arbitrary data, no sorting
    if rs:
        thread_paginator = rs.paginate(cur_page, per_page=threads_per_page,
            error_out=True)
        return thread_paginator

    # sexy line of code :)
    base_query = subreddit.threads if subreddit else Thread.query
    base_query = base_query.filter(Thread.status != 0).order_by(Thread.order.desc())  #非dead

    if trending:
        #https://stackoverflow.com/questions/16966163/sqlalchemy-order-by-calculated-column
        #我们用计算列的方式来置顶。可能有性能问题
        order_column = Thread.pin * 100000 + Thread.votes
        thread_paginator = base_query.order_by(db.desc(order_column)).\
        paginate(cur_page, per_page=threads_per_page, error_out=True)
    else:
        order_column = Thread.pin * 100000 + Thread.hotness
        thread_paginator = base_query.order_by(db.desc(order_column)).\
                paginate(cur_page, per_page=threads_per_page, error_out=True)
    return thread_paginator


#@mod.route('/<regex("trending"):trending>/')
@mod.route('/')
def home(trending=False):
    """
    If not trending we order by creation date
    """
    trending = True if request.args.get('trending') else False
    subreddits = get_subreddits()
    thread_paginator = process_thread_paginator(trending)

    return render_template('home.html', user=g.user,
            subreddits=subreddits, cur_subreddit=home_subreddit(),
            thread_paginator=thread_paginator)

@mod.route('/search/', methods=['GET'])
def search():
    """
    Allows users to search threads and comments
    """
    query = request.args.get('query')
    rs = search_module.search(query, orderby='creation', search_title=True,
            search_text=True, limit=100)

    thread_paginator = process_thread_paginator(rs=rs)
    rs = rs.all()
    num_searches = len(rs)
    subreddits = get_subreddits()

    return render_template('home.html', user=g.user,
            subreddits=subreddits, cur_subreddit=home_subreddit(),
            thread_paginator=thread_paginator, num_searches=num_searches)

@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """
    We had to do some extra work to route the user back to
    his or her original place before logging in
    """
    if g.user:
        return redirect(url_for('frontends.home'))

    next = ''
    if request.method == 'GET':
        if 'next' in request.args:
            next = request.args['next']

    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            session['user_id'] = user.id

            #总是前往用户中心
            # if 'next' in request.form and request.form['next']:
            #     return redirect(request.form['next'])
            return redirect(url_for('my.my_status'))


        flash(u'用户名或密码错误！', 'danger')
    return render_template("login.html", form=form, next=next)

@mod.route('/logout/', methods=['GET', 'POST'])
@requires_login
def logout():
    session.pop('user_id', None)
    return redirect(url_for('frontends.home'))

@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    """
    next = ''
    if request.method == 'GET':
        # flash(u'请妥善保管注册资料！', 'danger')
        if 'next' in request.args:
            next = request.args['next']

    form = RegisterForm(request.form)
    if form.validate_on_submit():

        if secode_validate():

            user = User(username=form.username.data, email=form.email.data, \
                    password=generate_password_hash(form.password.data))
            db.session.add(user)
            try:
                db.session.commit()
                session['user_id'] = user.id

                flash(u'欢迎新用户！', 'success')
                # 不再关心next，始终前往用户中心
                # if 'next' in request.form and request.form['next']:
                    # return redirect(request.form['next'])
                return redirect(url_for('my.my_status'))
            except Exception:
                flash(u'用户名或email已经被占用!', 'danger')
        else:
            flash(u'验证码错误!', 'danger')

    return render_template("register.html", form=form, next=next)

kongproject/kong/threads/views.py
# -*- coding: utf-8 -*-
"""
"""
from flask import (Blueprint, request, render_template, flash, g, session,
    redirect, url_for, abort)
from kong.threads.forms import SubmitForm
from kong.threads.models import Thread
from kong.threads import constants as THREAD
from kong.media import get_img_from_mkd
from kong.users.models import User
from kong.subreddits.models import Subreddit
from kong.frontends.views import get_subreddits
from kong import db
from kong.security.sec_util import secode_validate
import re

mod = Blueprint('threads', __name__, url_prefix='/threads')

#######################
#### Threads Views ####
#######################

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

def meets_thread_criterea(thread):
    """
    """
    if not thread.title:
        flash('You must include a title!', 'danger')
        return False
    if not thread.text and not thread.link:
        flash('You must post either body text or a link!', 'danger')
        return False

    # dup_link = Thread.query.filter_by(link=thread.link).first()
    # if not thread.text and dup_link:
    #     flash('someone has already posted the same link as you!', 'danger')
    #     return False

    return True


@mod.route('/<subreddit_name>/submit/', methods=['GET', 'POST'])
def submit(subreddit_name=None):
    """
    发issue
    """
    if g.user is None:
        flash('You must be logged in to submit issues!', 'danger')
        return redirect(url_for('frontends.login', next=request.path))
    user_id = g.user.id

    subreddit = Subreddit.query.filter_by(name=subreddit_name).first()
    if not subreddit:
        abort(404)

    form = SubmitForm(request.form)
    if form.validate_on_submit():
        if secode_validate() and g.user.is_admin():
            title = form.title.data.strip()
            link = form.link.data.strip()
            text = form.text.data.strip()
            thread = Thread(title=title, link=link, text=text,
                    user_id=user_id, subreddit_id=subreddit.id)
            thread.use_markdown = form.use_markdown.data
            thread.ttype = THREAD.TYPE_ARTICLE
            thread.thumbnail = None
            thread.order = form.order.data
            thread.path = form.path.data
            
            #暂时不做这个thumbnail
            # thumbnail = get_img_from_mkd(text)
            # if thumbnail and len(thumbnail) > 0:
            #     thread.thumbnail = thumbnail

            # 永远是article
            # if len(link) > 0:
            #     thread.ttype = THREAD.TYPE_LINK

            if not meets_thread_criterea(thread):
                print('>>>>a')
                return render_template('threads/submit.html', form=form, user=g.user,
                    cur_subreddit=subreddit.name)

            db.session.add(thread)
            db.session.commit()
            thread.set_hotness()

            flash('thanks for submitting!', 'success')
            return redirect(url_for('subreddits.permalink', subreddit_name=subreddit.name))
        else:
            print('>>>>b')
            flash(u'验证码错误！', 'danger')
    print('>>>>c')
    return render_template('threads/submit.html', form=form, user=g.user,
            cur_subreddit=subreddit, subreddits=get_subreddits())

@mod.route('/delete/', methods=['GET', 'POST'])
def delete():
    """
    """
    pass

@mod.route('/edit/', methods=['GET', 'POST'])
def edit():
    """
    """
    pass

@mod.route('/<subreddit_name>/<thread_id>/<path:title>/', methods=['GET', 'POST'])
def thread_permalink(subreddit_name=None, thread_id=None, title=None):
    """
    """
    thread_id = thread_id or -99
    thread = Thread.query.get_or_404(int(thread_id))
    subreddit = Subreddit.query.filter_by(name=subreddit_name).first()
    subreddits = get_subreddits()

    if thread and thread.status == 0:
        abort(404) #删除的thread无法查看
    else:
        thread.view += 1
        db.session.commit()


    return render_template('threads/permalink.html', user=g.user, thread=thread,
            cur_subreddit=subreddit, subreddits=subreddits)

##########################
##### Comments Views #####
##########################

@mod.route('/comments/submit/', methods=['GET', 'POST'])
def submit_comment():
    """
    """
    pass

@mod.route('/comments/delete/', methods=['GET', 'POST'])
def delete_comment():
    """
    """
    pass

@mod.route('/comments/<comment_id>/', methods=['GET', 'POST'])
def comment_permalink():
    """
    """
    pass

kongproject/kong/users/views.py
# -*- coding: utf-8 -*-
"""
"""
from flask import (Blueprint, request, render_template, flash, g, session,
    redirect, url_for, abort)

from kong import db
from kong.users.models import User
from kong.frontends.views import get_subreddits
from kong.users.decorators import requires_login

mod = Blueprint('users', __name__, url_prefix='/users')

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

@mod.route('/<username>/')
def home_page(username=None):
    if not username:
        abort(404)
    user = User.query.filter_by(username=username).first()
    if not user:
        abort(404)
    return render_template('users/profile.html', user=g.user, current_user=user,
            subreddits = get_subreddits())

kongproject/kong/views/my_view.py
# -*- coding: utf-8 -*-

from flask import (Blueprint, request, render_template, flash, g,
        session, redirect, url_for, jsonify, abort)
from werkzeug import check_password_hash, generate_password_hash

from kong import db
from kong.models.owm_model import Owm
from kong.users.models import User
from kong.threads.models import Thread, Comment
from kong.users.decorators import requires_login
from kong.apis.openlog import OpenLog
from kong.frontends.views import get_subreddits
from kong import utils
from kong.forms import AlterPasswordForm
import base64
import random
import json
import uuid


mod = Blueprint('my', __name__, url_prefix='/my')

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

@mod.route('/status/', methods=['GET', 'POST'])
@requires_login
def my_status():
    """
    我的用户中心。
    """
    owm = Owm.query.filter_by(user_id=g.user.id).first()
    data = dict(owm_left_day=0, owm_user_type="未激活")
    if owm:
        left_day = owm.pay_end_day - utils.get_today() + 1
        if left_day < 0:
            left_day = 0
        
        if left_day > (100*365):
            data['owm_left_day'] = u'永久'
        else:
            data['owm_left_day'] = left_day
            
        if left_day > 0:
            data['owm_user_type'] = u'VIP'
        else:
            data['owm_user_type'] = u'普通用户'


    return render_template('my/status.html', user=g.user, subreddits = get_subreddits(), data=data)


@mod.route('/alter-password/', methods=['GET', 'POST'])
@requires_login
def alter_password():
    """
    修改密码
    """

    form = AlterPasswordForm(request.form)
    if form.validate_on_submit():
        if check_password_hash(g.user.password, form.oldPassword.data):
            g.user.password = generate_password_hash(form.newPassword.data)
            db.session.commit()
            flash(u'密码已更新！', 'success')
        else:
            flash(u'密码错误!', 'danger')
    return render_template('my/alter-password.html', form=form, user=g.user, subreddits = get_subreddits())



@mod.route('/reset_password/', methods=['post'])
@requires_login
def reset_password():
    """
    admin，用来重置某个账号的密码为123456
    """
    username = request.form.get('username', default=None)
    if username and g.user.is_admin():
        user = User.query.filter_by(username=username).first()
        if user:
            user.password = generate_password_hash('123456')
            db.session.commit()
            return jsonify(err=0, msg="success")
        else:
            return jsonify(err=2, msg="user not found!")
    return jsonify(err=1, msg="Forbidden!")

kongproject/kong/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    {% block title %}
    {% if cur_subreddit is defined and cur_subreddit.id != 1%}
    <title>{{ cur_subreddit.name }} - {{ config.BRAND }}</title>
    <meta name="description" content="{{ cur_subreddit.desc }}">
    {% else %}
    <title>{{ config.BRAND }}</title>
    <meta name="description" content="{{ config.BRAND_DESC }}">
    {% endif %}

    {% endblock %}
    <meta name="keywords" content="kongproject">

    <!-- Bootstrap core CSS -->
    <!-- <link href="css/bootstrap.css" rel="stylesheet"> -->
    <link rel="icon" href="http://fate2.oss-cn-shanghai.aliyuncs.com/kong/kong_favicon.png" type="image/x-icon">
    {% block css %}
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/iconfont.css') }}">

    {% if cur_subreddit is defined %}
    <link rel="stylesheet" href="{{ cur_subreddit.cssfile }}">
    {% endif %}
    {% endblock %}
    <script src="//upcdn.b0.upaiyun.com/libs/jquery/jquery-2.0.3.min.js"></script>
    <script src="{{ url_for('static', filename='js/base.js') }}"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111452095-7"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-111452095-7');
    </script>


    {% if cur_subreddit is defined %}
    <style>
        {{ cur_subreddit.csstext }}
    </style>
    {% endif %}

</head>

<body>
    <div id="top_projects_bar">
        {% if subreddits is defined %}
        {% for subreddit in subreddits[:10] %}
        {% if subreddit.id != 1 %}
        <a class="top_projects_bar_item" href="/p/{{ subreddit.name }}">{{ subreddit.name }}</a>
        {% else %}
        <a class="top_projects_bar_item" href="/">首页</a>
        {% endif %}
        {% endfor %}
        {% endif %}
    </div>
    <div id="header_bar">

        {% if cur_subreddit is defined and cur_subreddit.id != 1%}
        <a id="header_img_wrapper" href="/p/{{ cur_subreddit.name }}">
            <img src="{{ cur_subreddit.icon }}" />
        </a>
        <a id="header_project_name" class="brand" href="/p/{{ cur_subreddit.name }}">
            {{ cur_subreddit.name }}
        </a>
        {% else %}
        <a id="header_img_wrapper" href="/">
            <img src="{{ config.BRAND_ICON }}" />
        </a>
        <a id="header_project_name" class="brand" href="/">
            {{config.BRAND}}
        </a>
        {% endif %}

        <!-- tabs -->
        <!-- <ul id="header_tabs" class="font-high">
                <li class="header-tab rank-type" r="all">
                    {% if cur_subreddit is defined and cur_subreddit.id != 1%}
                    <a href="/p/{{ cur_subreddit.name }}">ALL</a>
                    {% else %}
                    <a href="/">ALL</a>
                    {% endif %}
                </li>
                <li class="header-tab rank-type" r="pop">
                    {% if cur_subreddit is defined and cur_subreddit.id != 1%}
                    <a href="/p/{{ cur_subreddit.name }}/?r=pop">POP</a>
                    {% else %}
                    <a href="/?r=pop">POP</a>
                    {% endif %}
                </li>
            </ul> -->

        <div class="flex-push"></div>
        <ul id="user_corner">
            {% if user is not defined or user == None %}
            <!-- 未登录时 -->
            <a href="{{ url_for('frontends.register', next=request.path) }}">注册</a>
            <a href="{{ url_for('frontends.login', next=request.path) }}">登录</a>
            {% else %}
            <!-- 登录后 -->

            <a href="{{ url_for('users.home_page', username=user.username) }}">
                {{ user.username }}</a>

            <a href="{{ url_for('my.my_status') }}">
                    [用户中心]</a>
            <span>
                {{ user.get_thread_karma() }} <span class="karma-star">★</span></span>

            <a href="{{ config.ROOT_URL }}/logout">退出</a>
                
            {% endif %}
        </ul>
    </div>
    <div id="fixed_position_devider"></div>
    <div id="project_intro_bar">

    </div>


    <div>
            <div id="messages">
                {% for category, msg in get_flashed_messages(with_categories=true) %}
                <div class="message-item flash-{{ category }} alert alert-dismissable alert-{{ category }} flash-banner">
                    {{ msg }}
                </div>
                {% endfor %}
            </div>

            <div id="main_content">
                {% block content %}

                {% endblock %}
            </div>

            <div class="row" class="" id="footer-row">
                <div class="col-lg-12">
                </div>
            </div>

    </div>


        <!-- JavaScript -->
        <!-- TODO google ana -->

        <!-- Let's use a CDN -->
        {% block scripts %}

        {% endblock %}
    <footer>
        <style>
            footer{
                text-align: center;      
            }
            footer, footer a{
                font-size: 13px;
                color: #999;
            }
        </style>
        &copy; 2019 fatecore.com <br/>

        <a href="http://www.miitbeian.gov.cn/">浙ICP备17048489号-26</a>

    </footer>
</body>

</html>

kongproject/kong/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="left-bar">
    {% if cur_subreddit is defined %}

    <div class="channel-header markdown row">
        <!-- 注意markdown内容部分必须紧跟着filter -->
        {% filter markdown %}{{ cur_subreddit.submit_note }}
        {% endfilter %}
    </div>

    {% endif %}

    {% block left %}
    {% if num_searches is defined %}
    <h4 class="highlight" style="margin-left: 10px;">搜索到 {{ num_searches }} 个内容。 </h4>
    <br>
    {% endif %}
    <div class="spacer"></div>
    {% for thread in thread_paginator.items %}
    <div name="{{ thread.id }}" class="listing-row thread" pin="{{ thread.pin}}">
        <div class="listing-vote-box">
            <div class="">
                {% if user is defined and user != None and thread.has_voted(user.id) %}
                <a data-voted="true" style="color:#eb6864;" href="javascript:void(0)" class="listing-vote-button">▲</a>
                {% else %}
                <a data-voted="false" style="color:#000;" href="javascript:void(0)" class="listing-vote-button">▲</a>
                {% endif %}
            </div>
            <div class="listing-votes-number">
                {{ thread.votes }}
            </div>
        </div>
        <div class="listing-thumbnail-box">
            <!-- <img class="listing-image" src="{{ thread.thumbnail|replace("http://", "https://") }}" /> -->
        </div>
        <div class="listing-text">
            {% if thread.link %}
            <a href="{{ thread.link }}" class="listing-title">
                {% else %}
                <a href="{{ config.ROOT_URL }}/threads/{{ thread.subreddit.name }}/{{ thread.id }}/{{ thread.path|truncate(100)|replace(' ', '_') }}"
                    class="listing-title">
                    {% endif %}
                    <h4 class="listing-title-text">
                        {% if thread.pin %}
                        <span class="iconfont icon-top"></span>
                        {% endif %}
                        {{ thread.title }}
                    </h4>
                </a>

                <div class="post-listing-meta">
                    <!-- <a
                        href="{{ config.ROOT_URL }}/threads/{{ thread.subreddit.name }}/{{ thread.id }}/{{ thread.title|truncate(100)|replace(' ', '_') }}">
                        {{ thread.comments.all()|length() }} comments</a>, -->
                    <i class="iconfont icon-date"></i>
                        {{ thread.pretty_date() }}
                        <i class="iconfont icon-icon_writer"></i>
                    <a href="{{ url_for('users.home_page', 
                        username=thread.user.username) }}">
                        {{ thread.user.username }}</a>
                    
                        /
                    <a href="{{ url_for('subreddits.permalink', 
                        subreddit_name=thread.subreddit.name) }}">
                        {{ thread.subreddit.name }}
                    </a>
                    
                    <i class="iconfont icon-eye"></i>
                    {{thread.view}} 
                </div>
        </div>
    </div>
    {% endfor %}

    <div class="pager pull-left">
        {% if thread_paginator.has_prev %}
        <a class="btn" href="?page={{ thread_paginator.prev_num }}">上一页</a>
        {% else %}
        <a class="btn" style="opacity:0.3;">上一页</a>
        {% endif %}
        {% if thread_paginator.has_next %}
        <a class="btn" href="?page={{ thread_paginator.next_num }}">下一页</a>
        {% else %}
        <a class="btn" style="opacity:0.3;">下一页</a>
        {% endif %}
    </div>
    {% endblock %}
</div>

<div id="right_bar">
    {% block right %}
    {% if user is defined and user != None %}
    <!-- -->
    {% else %}
    <!-- <h4 class="pre-reg-info">Please register or login to post!</h4>-->
    {% endif %}
    {% block create_buttons %}
    <div>
        {% block user_dashboard %}
        {% endblock %}
        <form method="GET" action="/search/" class="row" role="search">
            <div class="form-group">
                <input type="text" name="query" class="input" placeholder="搜索泡核">
            </div>
            <!--<button type="submit" class="btn btn-default">Submit</button>-->
        </form>
        {% if user != None and user.is_super() %}
        <!-- super区域 -->
        {% if cur_subreddit is defined %}
        <a class="row" href="{{ url_for('threads.submit', subreddit_name=cur_subreddit.name) }}">
            <button class="btn btn-primary submit-post-button">
                发帖 到 {{ cur_subreddit.name }}
            </button>
        </a>
        {% else %}
        <a class="row" href="{{ url_for('threads.submit', subreddit_name='frontpage') }}">
            <button class="btn btn-primary submit-post-button">
                发帖
            </button>
        </a>
        {% endif %}

        <a href="{{ url_for('subreddits.submit') }}">
            <button type="button" class="btn btn-primary 
                inverse-white-button add-subreddit-button">
                创建project
            </button>
        </a>
        {% endif %}
    </div>

    {% if cur_subreddit is defined %}
    <p class="subreddit-desc">
        {{ cur_subreddit.desc }}
    </p>

    <div class="subreddit-intro markdown row">
        <!-- 注意markdown内容部分必须紧跟着filter -->
        {% filter markdown %}{{ cur_subreddit.intro }}
        {% endfilter %}
    </div>


    {% if user.role == 2 %}
    <!-- project编辑入口 -->

    <a href="{{ url_for('subreddits.edit', subreddit_name=cur_subreddit.name) }}">
        [编辑{{ cur_subreddit.name }}]</a>
    {% endif %}

    {% endif %}

    {% endblock %}
    <!-- 
    <h4 class="subreddit-desc">相关Projects</h4>
    <ul id="subreddit-list">
        {% for subreddit in subreddits[:10] %}
        <li><a href="/p/{{ subreddit.name }}">{{ subreddit.name }}</a></li>
        {% endfor %}
    </ul>
    <a class="align-right-col" href="{{ url_for('subreddits.view_all') }}">view all</a> -->


    <div class="row" id="foot_corner">

        &copy;{{ config.BRAND }}

        <br />
        <a href="http://www.miitbeian.gov.cn/">浙ICP备17048489号-26</a>
        <br />
        <div style="opacity: 0;">
            友链:
            <a href="https://github.com/fate233">Github</a><br />
            <a href="https://www.netqon.com">Netqon</a><br />
        </div>
    </div>
</div>

</i>
{% endblock %}
</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function () {
        $(document).on('click', 'a.listing-vote-button', function () {
            var $vote_button = $(this); // cache this! can't access in callback!
            var thread_id = $vote_button.parent().parent().parent().attr('name');
            var post_to = '/apis/threads/vote/';
            if ($vote_button.attr("data-voted") === "true") {
                $vote_button.css("color", "#000");
                $vote_button.attr("data-voted", "false");
            } else {
                $vote_button.css("color", "rgb(235, 104, 100)");
                $vote_button.attr("data-voted", "true");
            }
            //路人也能vote //注意了，template注释无效
            console.log('vote')
            $.post(post_to, { thread_id: thread_id },
                function (response) {
                    var new_vote_count = response.new_votes.toString();
                    var vote_status = response.vote_status;
                    $vote_button.parent().parent().
                        children('div.listing-votes-number').html(new_vote_count);
                }, 'json'
            );

        });
    });
</script>
{% endblock %}

kongproject/kong/templates/login.html
{% extends "base.html" %}
{% block content %}
<div id="login_box">
    <h1 class="row text-center login-title">Login</h1>
    <div class="account-wall">
        <!-- <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120"
                    alt=""> -->
        {% from "macros.html" import render_field %}
        <form method="POST" action="." class="form-signin">
            {{ form.csrf_token }}
            <input type="hidden" name="next" value="{{ next }}" />
            {{ render_field(form.username, class="form-control", 
                    placeholder="username", autofocus="") }}
            {{ render_field(form.password, class="form-control", placeholder="password") }}
            <button class="btn btn-lg btn-primary btn-block" type="submit">
                登录</button>
            <!--
                <label class="checkbox pull-left">
                    <input type="checkbox" value="remember-me">
                    Remember me
                </label>
                -->
        </form>
    </div>
    <div class="row">
            <a href="{{ url_for('frontends.register') }}" class=" text-center new-account" >创建账号 </a>
    </div>
</div>
{% endblock %}

kongproject/kong/templates/macros.html
{% macro render_field(field) %}
  <div class="form_field">
  <!--{ field.label(class="label") }}-->
  {% if field.errors %}
    {% set css_class = 'has_error ' + kwargs.pop('class', '') %}
    {{ field(class=css_class, **kwargs) }}
    <div class="alert alert-dismissable alert-danger">{% for error in field.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
  {% else %}
    {{ field.label}}
    {{ field(**kwargs) }}
  {% endif %}
  </div>
{% endmacro %}

kongproject/kong/templates/register.html
{% extends "base.html" %}

{% block content %}
<div id="login_box">
    {% from "macros.html" import render_field %}
    <form method="POST" action="." class="form bs-example form-horizontal">
      {{ form.csrf_token }}
      <input type="hidden" name="next" value="{{ next }}" />
      {{ render_field(form.username, class="form-control", placeholder="username", autofocus="") }}
      <br>
      {{ render_field(form.email, class="form-control", placeholder="email") }}
      <br>
      {{ render_field(form.password, class="form-control", placeholder="password") }}
      <br>
      {{ render_field(form.confirm, class="form-control", placeholder="confirm password") }}
      <br>
      {{ render_field(form.accept_tos, class="form-control") }}
      <a href="/threads/FateCore/47/User-Protocal/" target="_blank">《用户服务协议》</a> <br /> <br />
      <img id="secode" src="{{ url_for('security.secode')}}?_t=">
      {{ render_field(form.secode, class="form-control", placeholder="验证码", autocomplete="off") }}

      <br>

      <button type="submit" value="Register" class="btn btn-primary">注册</button>
    </form>
</div>
{% endblock %}