kongproject/kong/threads/forms.py
# -*- coding: utf-8 -*-
"""
"""
from kong.threads import constants as THREAD
from flask_wtf import Form
from wtforms import TextField, TextAreaField, BooleanField, IntegerField
from wtforms.validators import Required, URL, Length, Optional

class SubmitForm(Form):
    title = TextField('Title', [Required()])
    text = TextAreaField('Content', [Required()]) # [Length(min=5, max=THREAD.MAX_BODY)]
    link = TextField('Ref Link', [Optional(), URL(require_tld=True,
        message="That is not a valid link url!")])
    use_markdown = BooleanField('As Markdown')
    secode = TextField('Captcha', [Optional()]) #不做判断的，因为只有admin能发帖
    order = IntegerField('Order', [Optional()], default=0)
    path = TextField('Path', [Required()])

kongproject/kong/frontends/views.py
# -*- coding: utf-8 -*-
"""
"""
from flask import (Blueprint, request, render_template, flash,
    g, session, redirect, url_for)
from werkzeug import check_password_hash, generate_password_hash

from kong import db
from kong import search as search_module # don't override function name
from kong.users.forms import RegisterForm, LoginForm
from kong.users.models import User
from kong.threads.models import Thread
from kong.subreddits.models import Subreddit
from kong.users.decorators import requires_login
from kong.security.sec_util import secode_validate

mod = Blueprint('frontends', __name__, url_prefix='')

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

def home_subreddit():
    return Subreddit.query.get_or_404(1)

def get_subreddits():
    """
    important and widely imported method because a list of
    the top 30 subreddits are present on every page in the sidebar
    """
    subreddits = Subreddit.query.all()[:25]
    return subreddits

def process_thread_paginator(trending=False, rs=None, subreddit=None):
    """
    abstracted because many sources pull from a thread listing
    source (subreddit permalink, homepage, etc)
    """
    threads_per_page = 15
    cur_page = request.args.get('page') or 1
    cur_page = int(cur_page)
    thread_paginator = None

    # if we are passing in a resultset, that means we are just looking to
    # quickly paginate some arbitrary data, no sorting
    if rs:
        thread_paginator = rs.paginate(cur_page, per_page=threads_per_page,
            error_out=True)
        return thread_paginator

    # sexy line of code :)
    base_query = subreddit.threads if subreddit else Thread.query
    base_query = base_query.filter(Thread.status != 0).order_by(Thread.order.desc())  #非dead

    if trending:
        #https://stackoverflow.com/questions/16966163/sqlalchemy-order-by-calculated-column
        #我们用计算列的方式来置顶。可能有性能问题
        order_column = Thread.pin * 100000 + Thread.votes
        thread_paginator = base_query.order_by(db.desc(order_column)).\
        paginate(cur_page, per_page=threads_per_page, error_out=True)
    else:
        order_column = Thread.pin * 100000 + Thread.hotness
        thread_paginator = base_query.order_by(db.desc(order_column)).\
                paginate(cur_page, per_page=threads_per_page, error_out=True)
    return thread_paginator


#@mod.route('/<regex("trending"):trending>/')
@mod.route('/')
def home(trending=False):
    """
    If not trending we order by creation date
    """
    trending = True if request.args.get('trending') else False
    subreddits = get_subreddits()
    thread_paginator = process_thread_paginator(trending)

    return render_template('home.html', user=g.user,
            subreddits=subreddits, cur_subreddit=home_subreddit(),
            thread_paginator=thread_paginator)

@mod.route('/search/', methods=['GET'])
def search():
    """
    Allows users to search threads and comments
    """
    query = request.args.get('query')
    rs = search_module.search(query, orderby='creation', search_title=True,
            search_text=True, limit=100)

    thread_paginator = process_thread_paginator(rs=rs)
    rs = rs.all()
    num_searches = len(rs)
    subreddits = get_subreddits()

    return render_template('home.html', user=g.user,
            subreddits=subreddits, cur_subreddit=home_subreddit(),
            thread_paginator=thread_paginator, num_searches=num_searches)

@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """
    We had to do some extra work to route the user back to
    his or her original place before logging in
    """
    if g.user:
        return redirect(url_for('frontends.home'))

    next = ''
    if request.method == 'GET':
        if 'next' in request.args:
            next = request.args['next']

    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            session['user_id'] = user.id

            #总是前往用户中心
            # if 'next' in request.form and request.form['next']:
            #     return redirect(request.form['next'])
            return redirect(url_for('my.my_status'))


        flash(u'用户名或密码错误！', 'danger')
    return render_template("login.html", form=form, next=next)

@mod.route('/logout/', methods=['GET', 'POST'])
@requires_login
def logout():
    session.pop('user_id', None)
    return redirect(url_for('frontends.home'))

@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    """
    next = ''
    if request.method == 'GET':
        # flash(u'请妥善保管注册资料！', 'danger')
        if 'next' in request.args:
            next = request.args['next']

    form = RegisterForm(request.form)
    if form.validate_on_submit():

        if secode_validate():

            user = User(username=form.username.data, email=form.email.data, \
                    password=generate_password_hash(form.password.data))
            db.session.add(user)
            try:
                db.session.commit()
                session['user_id'] = user.id

                flash(u'欢迎新用户！', 'success')
                # 不再关心next，始终前往用户中心
                # if 'next' in request.form and request.form['next']:
                    # return redirect(request.form['next'])
                return redirect(url_for('my.my_status'))
            except Exception:
                flash(u'用户名或email已经被占用!', 'danger')
        else:
            flash(u'验证码错误!', 'danger')

    return render_template("register.html", form=form, next=next)

kongproject/kong/subreddits/views.py
# -*- coding: utf-8 -*-
"""
"""
from flask import (Blueprint, request, render_template, flash, g,
                   session, redirect, url_for, abort)

from kong.frontends.views import get_subreddits, process_thread_paginator
from kong.subreddits.forms import SubmitForm
from kong.threads.forms import SubmitForm as ThreadForm
from kong.subreddits.models import Subreddit
from kong.threads.models import Thread
from kong.users.models import User
from kong import db
from kong import utils
from kong.security.sec_util import secode_validate
from kong.media import get_img_from_mkd

mod = Blueprint('subreddits', __name__, url_prefix='/p')

#######################
### Subreddit Views ###
#######################


@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])


def meets_subreddit_criterea(subreddit):
    return True


@mod.route('/subreddits/submit/', methods=['GET', 'POST'])
def submit():
    """
    """
    if g.user is None:
        flash('You must be logged in to submit subreddits!', 'danger')
        return redirect(url_for('frontends.login', next=request.path))

    form = SubmitForm(request.form)

    if not g.user.is_admin():
        flash(u'我没有权限创建project!', 'danger')
        return render_template('subreddits/submit.html', form=form, user=g.user,
                               subreddits=get_subreddits())

    user_id = g.user.id

    if form.validate_on_submit():
        name = form.name.data.strip()
        desc = form.desc.data.strip()

        subreddit = Subreddit.query.filter_by(name=name).first()
        if subreddit:
            flash('project already exists!', 'danger')
            return render_template('subreddits/submit.html', form=form, user=g.user,
                                   subreddits=get_subreddits())
        new_subreddit = Subreddit(name=name, desc=desc, admin_id=user_id)
        
        icon = form.icon.data.strip()
        if len(icon) > 0:
            new_subreddit.icon = icon
        
        new_subreddit.intro = form.intro.data
        new_subreddit.submit_note = form.submit_note.data
        new_subreddit.csstext = form.csstext.data

        if not meets_subreddit_criterea(subreddit):
            return render_template('subreddits/submit.html', form=form, user=g.user,
                                   subreddits=get_subreddits())

        db.session.add(new_subreddit)
        db.session.commit()

        flash('Thanks for starting a project! Begin adding issues to your project\
                by clicking the red button to the right.', 'success')
        return redirect(url_for('subreddits.permalink', subreddit_name=new_subreddit.name))
    return render_template('subreddits/submit.html', form=form, user=g.user,
                           subreddits=get_subreddits())


@mod.route('/subreddits/edit/<subreddit_name>/', methods=['GET', 'POST'])
def edit(subreddit_name):
    """
    """
    if g.user is None:
        flash('You must be logged in to edit subreddits!', 'danger')
        return redirect(url_for('frontends.login', next=request.path))

    subreddit = Subreddit.query.filter_by(name=subreddit_name).first()

    if not subreddit:
        abort(404)
    
    form = SubmitForm(request.form)
    if not form.name.data:
        form.name.data = subreddit.name
        form.desc.data = subreddit.desc
        form.icon.data = subreddit.icon
        form.intro.data = subreddit.intro
        form.submit_note.data = subreddit.submit_note
        form.csstext.data = subreddit.csstext

    if not g.user.is_admin():
        flash(u'我没有权限编辑Project!', 'danger')
        return render_template('subreddits/submit.html', form=form, user=g.user,
                               subreddits=get_subreddits())

    user_id = g.user.id

    if form.validate_on_submit():
        subreddit.name = form.name.data.strip()
        subreddit.desc = form.desc.data.strip()
        subreddit.icon = form.icon.data.strip()
        subreddit.intro = form.intro.data.strip()
        subreddit.submit_note = form.submit_note.data.strip()
        subreddit.csstext = form.csstext.data.strip()
        db.session.commit()

        flash('Project edit success!', 'success')
        return redirect(url_for('subreddits.permalink', subreddit_name=subreddit.name))
    return render_template('subreddits/submit.html', form=form, user=g.user,
                           subreddits=get_subreddits())

@mod.route('/delete/', methods=['GET', 'POST'])
def delete():
    """
    """
    pass


@mod.route('/subreddits/view_all/', methods=['GET'])
def view_all():
    """
    """
    return render_template('subreddits/all.html', user=g.user,
                           subreddits=Subreddit.query.all())


@mod.route('/<subreddit_name>/', methods=['GET'])
def permalink(subreddit_name=""):
    """
    """
    subreddit = Subreddit.query.filter_by(name=subreddit_name).first()
    if not subreddit:
        abort(404)

    trending = True if request.args.get('trending') else False
    thread_paginator = process_thread_paginator(
        trending=trending, subreddit=subreddit)
    subreddits = get_subreddits()

    return render_template('home.html', user=g.user, thread_paginator=thread_paginator,
                           subreddits=subreddits, cur_subreddit=subreddit)


@mod.route('/edit/<subreddit_name>/<thread_id>/', methods=['GET', 'POST'])
def thread_edit(subreddit_name=None, thread_id=None):
    """
    """
    if g.user is None:
        flash('You must be logged in to edit issue!', 'danger')
        return redirect(url_for('frontends.login', next=request.path))

    form = ThreadForm(request.form)
    thread = Thread.query.filter_by(id=thread_id).first()
    if thread == None or thread.user_id != g.user.id:
        abort(403)


    if len(form.title.data) <= 0:
        form.title.data = thread.title
        form.text.data = thread.text
        form.use_markdown.data = thread.use_markdown
        form.link.data = thread.link
        form.order.data = thread.order
        form.path.data = thread.path

    if form.validate_on_submit():
        if secode_validate():
            thread.title = form.title.data
            thread.link = form.link.data
            thread.text = form.text.data
            thread.use_markdown = form.use_markdown.data
            thread.order = form.order.data
            thread.path = form.path.data
            
            thumbnail = get_img_from_mkd(thread.text)
            if thumbnail and len(thumbnail) > 0:
                thread.thumbnail = thumbnail

            db.session.commit()

            flash(u'编辑成功', 'success')
            return redirect(url_for('threads.thread_permalink', subreddit_name=subreddit_name, thread_id=thread.id, title=thread.path))
        else:
            flash(u'验证码错误！', 'danger')
    
    return render_template('threads/submit.html', form=form, user=g.user,
                           subreddits=get_subreddits())

kongproject/kong/threads/__init__.py
# -*- coding: utf-8 -*-

kongproject/kong/users/views.py
# -*- coding: utf-8 -*-
"""
"""
from flask import (Blueprint, request, render_template, flash, g, session,
    redirect, url_for, abort)

from kong import db
from kong.users.models import User
from kong.frontends.views import get_subreddits
from kong.users.decorators import requires_login

mod = Blueprint('users', __name__, url_prefix='/users')

@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])

@mod.route('/<username>/')
def home_page(username=None):
    if not username:
        abort(404)
    user = User.query.filter_by(username=username).first()
    if not user:
        abort(404)
    return render_template('users/profile.html', user=g.user, current_user=user,
            subreddits = get_subreddits())

kongproject/kong/templates/threads/permalink.html
{% extends "home.html" %}

{% block left %}
<div name="{{ thread.id }}" class="row listing-row thread-permalink">
    <div class="col-lg-1 listing-vote-box">
        <div class="">
            {% if user is defined and user != None and thread.has_voted(user.id) %}
            <a data-voted="true" style="color:#eb6864;" href="javascript:void(0)" class="listing-vote-button">▲</a>
            {% else %}
            <a data-voted="false" style="color:#000;" href="javascript:void(0)" class="listing-vote-button">▲</a>
            {% endif %}
        </div>
        <div class="listing-votes-number">
            {{ thread.votes }}
        </div>
    </div>
    <div class="col-lg-1 listing-thumbnail-box">
        <!-- <img class="permalink-listing-image" src="{{ thread.thumbnail|replace("http://", "https://") }}" /> -->
    </div>
    <div class="col-lg-9 listing-text">
        <a href="{{ thread.link }}">
            <h2 class="listing-title">{{ thread.title }}</h2>
        </a>
        created {{ thread.pretty_date('created') }},
        by <a href="{{ url_for('users.home_page', username=thread.user.username) }}">
            {{ thread.user.username }}</a> in <a href="{{ url_for('subreddits.permalink', 
                subreddit_name=thread.subreddit.name) }}">{{
            thread.subreddit.name }}</a>.
        {{ thread.view }} viewer.
        {% if thread.user.id == user.id %}
        <!-- 如果是自己，则显示编辑按钮 -->
        <a class="admin-btn"
            href="{{ url_for('subreddits.thread_edit', subreddit_name=thread.subreddit.name, thread_id=thread.id) }}">
            [编辑]</a>
        {% endif %}

        {% if user.role == 2 %}
        <!-- 管理区域 -->
        <a class="admin-btn" href="#" onclick="toggle_pin({{ thread.id }})">
            {% if thread.pin == 0 %}
            [置顶]
            {% else %}
            [取消置顶]
            {% endif%}
        </a>

        <a class="admin-btn" href="#" onclick="delete_thread({{ thread.id }})">[删除]</a>
        {% endif %}
        <div class="thread-content markdown">
            <!-- 注意markdown的内容必须贴着filter，否则解析有问题 -->
            {% filter markdown %}{{ thread.text }}
            {% endfilter %}
            <!--        现在强制使用Markdown了        
            {% if thread.use_markdown == 0 %}
            {{ thread.text }}
            {% else %}
            {% filter markdown %}{{ thread.text }}
            {% endfilter %}
            {% endif %} -->
        </div>
    </div>
</div>
<!-- 
<div id="comment_box">
    <div class="col-lg-6 thread-comment-section">
        {% if user is defined and user != None %}
        <h4>回复</h4>
        <div class="comment-form-parent">
            <textarea class="mlinput form-control thread-comment-box" style="width: 100%; max-width:300px;"></textarea>
            <button class="btn btn-sm btn-primary submit-comment main-submit">
                发送</button>
        </div>
        {% else %}
        <br>
        <i>
            <a href="{{ url_for('frontends.login') }}">登录</a> or
            <a href="{{ url_for('frontends.register') }}">注册</a> 来回复!
        </i>
        {% endif %}
    </div>

    <h4>评论</h4>

    <div class="row comments-tree">
        {%- for comment in thread.get_comments() recursive %}
        <div class="row comments-element" style="margin-left:{{ comment.get_margin_left() }}" name="{{ comment.id }}">
            <p class="comment-body">{{ comment.text }}</p>
            <div class="post-listing-meta">
                by: <a href="{{ url_for('users.home_page', username=comment.user.username) }}">
                    {{ comment.user.username }}</a> {{ comment.pretty_date() }}
                <a href="javascript:void(0)" class="comment-reply">回复</a>
            </div>

                <textarea class="mlinput nested-comment-text-box form-control" style="display:none;"></textarea>
                <button class="btn btn-sm btn-primary submit-comment nested-submit-comment-button" style="display:none;">
                        发送</button>
        </div>
        {%- if comment.get_comments() -%}
        {{ loop(comment.get_comments()) }}
        {%- endif %}
        {%- endfor %}
    </div>
</div>

<br>
<br> -->

{% endblock %}

{% block scripts %}
{{ super() }}
<!-- 
<script type="text/javascript">
    $(document).ready(function () {
        $(document).on('click', 'button.submit-comment', function () {
            // We will submit user id data via session.
            // Don't need to include parent comment because we are commenting 
            // on a thread, not a comment!
            var parent_id = "";
            var comment_text = "";
            var not_nested = $(this).hasClass('main-submit').toString();
            var $parent_comment = $(this).parent('div.comments-element');
            // the logic is funky because we are using string booleans...
            if (not_nested == 'false') {
                // it is nested 
                parent_id = $(this).parent('div.comments-element').attr('name');
                $comment_box = $(this).parent('div.comments-element').children(
                    'textarea.nested-comment-text-box')
                $button_box = $(this).parent('div.comments-element').children(
                    'button.nested-submit-comment-button');
                comment_text = $comment_box.val();
                $comment_box.val('');
                $button_box.toggle();
                $comment_box.toggle();

            } else {
                // it isn't nested
                $comment_box = $(this).parent('div.comment-form-parent').children(
                    'textarea.thread-comment-box');
                comment_text = $comment_box.val();
                $comment_box.val('');
            }

            if (comment_text == null || comment_text == '') {
                alert("Please enter a valid comment!");
                return;
            }

            var thread_id = "{{ thread.id }}";
            var post_to = '/apis/comments/submit/';
            {% if user is defined and user != None %}
            $.post(post_to, {
                parent_id: parent_id, // empty if top-level (none)
                thread_id: thread_id,
                comment_text: comment_text
            },
                function (response) {
                    var write_string =
                        '<div class="row comments-element" name="' + response.comment_id + '"' +
                        'style="margin-left:' + response.margin_left + '">' +
                        '<p class="comment-body">' + response.comment_text + '</p>' +
                        '<div class="post-listing-meta">' +
                        'by: <a href="{{ config.ROOT_URL }}/users/{{ user.username }}/">' +
                        '{{ user.username }}</a>' +
                        ' ' + response.date +
                        ' <a href="javascript:void(0)" class="comment-reply">回复</a>' +
                        '</div>' +
                        '<textarea class="nested-comment-text-box form-control" style="display:none;"></textarea>' +
                        '<button class="btn btn-sm btn-primary submit-comment ' +
                        'nested-submit-comment-button" style="display:none;">发送</button>';

                    if (not_nested == 'true') {
                        $('div.comments-tree').prepend(write_string);
                    } else {
                        $parent_comment.after(write_string);
                    }
                }, 'json'
            );
            {% else %}
            alert("You must be logged in to do that!");
            {% endif %}
        });

        $(document).on('click', 'a.comment-reply', function (e) {
            $(this).parent().parent().children('textarea.nested-comment-text-box').toggle();
            $(this).parent().parent().children('button.nested-submit-comment-button').toggle();
        });
    });
</script> -->
{% endblock %}

kongproject/kong/templates/threads/submit.html
{% extends "home.html" %}

{% block left %}
  <div >
  <br>
  <div class="col-lg-10 thread-submit-box">
  {% from "macros.html" import render_field %}
  <form method="POST" action="." class="form bs-example form-horizontal">
    {{ form.csrf_token }}
    {{ render_field(form.title, class="form-control ", placeholder="", autofocus="") }}
    <br>
    {{ render_field(form.path, class="form-control ", placeholder="") }}
    <br>
    {{ render_field(form.link, class="form-control ", placeholder="") }}
    <br>
    {{ render_field(form.text, class="form-control  ", placeholder="") }}
    <br>
    {{ render_field(form.order, class="form-control  ", placeholder="") }}
    <br>
    {{ render_field(form.use_markdown, class="form-control") }}
    <br>
    <img id="secode" src="{{ url_for('security.secode')}}?_t=" >
    {{ render_field(form.secode, class="form-control input", placeholder="验证码", autocomplete="off") }}
    <br>
    <button type="submit" value="Submit" class="btn btn-primary">提交（需审核）</button>
  </form>
  </div>
  </div> 
{% endblock %}